model:
  _target_: gans.ThreePlayerGAN
  data_dim:
    - 1
    - 28
    - 28
  code_size: 64

  critic:
    _target_: models.simple.mnistnet_d

  generator:
    _target_: models.simple.mnistnet_g

  transport:
    _target_: models.simple.mnistnet_h

  noise_distribution:
    _target_: distributions.Normal

  critic_step_period: 20
  generator_step_period: 10
  transport_step_period: 1
  l: .01
  p: 2.0
  reversed: true


optimizer:
  _target_: torch.optim.Adam
  lr: 2e-3
  betas:
    - 0.5
    - 0.999
  weight_decay: 1e-5

datamodule:
  _target_: datamodules.MNISTDataModule
  batch_size: 128
  num_workers: 4
  root: "data/"

trainer:
  log_every_n_steps: 20
  # gpus: 1
  max_epochs: 30
