model:
  _target_: gans.Wasserstein1GAN
  data_dim:
    - 3
    - 64
    - 64
  code_size: 1000

  critic:
    _target_: models.custom_resnet.resnet14_d

  generator:
    _target_: models.custom_resnet.resnet18_g

  noise_distribution:
    _target_: distributions.Normal

  weight_range: 0.01
  critic_step_period: 1
  generator_step_period: 1

optimizer:
  _target_: torch.optim.Adam
  lr: 2e-3
  betas:
    - 0.5
    - 0.999
  weight_decay: 1e-5

datamodule:
  _target_: datamodules.CelebADataModule
  batch_size: 32
  num_workers: 4
  root: "../data/"

trainer:
  log_every_n_steps: 20
  # gpus: 1
  max_epochs: 30
